version: '3.7'
services:
  jenkins:
    build: .
    ports:
      - 8888:8080
    container_name: jenkins-custom
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: {}
